### ISSUE TITLE
build faild, Unable to find "skiaview.h" header file

### ISSUE THREAD

**Issue by XaviorXiao** [lvpengwei/skiatext#1]
Do you need to rely on any environment

**Comment by lvpengwei** [comment]
Have you run `pod install` at `skiatext/examples/ios/SkiaTextDemo/`?

**Comment by XaviorXiao** [comment]
Sure


发自我的iPhone

------------------ Original ------------------

**Comment by lvpengwei** [comment]
I didn't reproduce

**Comment by XaviorXiao** [comment]
Can you send me a local.zip package? Thank you so much。


------------------ 原始邮件 ------------------
发件人: "lvpengwei"<notifications@github.com>;
发送时间: 2019年7月22日(星期一) 上午10:16
收件人: "lvpengwei/skiatext"<skiatext@noreply.github.com>;
抄送: "枫之诺"<1184689075@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lvpengwei/skiatext] build faild, Unable to find "skiaview.h"header file (#1)




I didn't reproduce

**Comment by lvpengwei** [comment]
skiatext.zip
<https://drive.google.com/file/d/1GDu9jN67yMTeuD5_AHCKRm8zesiP78rn/view?usp=drive_web>


XaviorXiao <notifications@github.com> 于2019年7月22日周一 上午11:28写道：

**Comment by XaviorXiao** [comment]
Sorry, I can't access Google. Can you send it to email directly? Email address: 1184689075@qq.com.




------------------ 原始邮件 ------------------
发件人: "lvpengwei"<notifications@github.com>;
发送时间: 2019年7月22日(星期一) 中午11:31
收件人: "lvpengwei/skiatext"<skiatext@noreply.github.com>;
抄送: "枫之诺"<1184689075@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lvpengwei/skiatext] build faild, Unable to find "skiaview.h"header file (#1)



 skiatext.zip
 <https://drive.google.com/file/d/1GDu9jN67yMTeuD5_AHCKRm8zesiP78rn/view?usp=drive_web>
 
 
 XaviorXiao <notifications@github.com> 于2019年7月22日周一 上午11:28写道：

**Comment by lvpengwei** [comment]
Done.
